apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-example
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
        aadpodidbinding: aad_pod_selector
    spec:
      containers:
      - name: example-container
        image: storage93594acr.azurecr.io/azure-storage-example:1
        env:
        ports: 
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ser-example
spec:
  selector:
    app: example-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingr-example
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: ser-example
          servicePort: 80
